### ISSUE TITLE
Download real data

### ISSUE THREAD

**Issue by skarbs001** [turpaultn/DESED#10]
Hi.

When I run create_dcase2019_dataset.sh, I got following this errors.

0     Y8lhDSLRfZ8Q_350.000_360.000.wav  ERROR: This video is unavailable.\n...
1       Y8Y3du2Iw0v4_60.000_70.000.wav  ERROR: This video is unavailable.\n...
2        Y97oxHi3qxs8_0.000_10.000.wav  ERROR: This video is unavailable.\n...
3       Y99MfwDS1Vpc_30.000_40.000.wav  ERROR: This video is unavailable.\n...
4     Y9aNXDP2rv7o_220.000_230.000.wav  ERROR: This video is unavailable.\n...
...                                ...                                                ...
1163    Y-4pmCrSdMhg_30.000_40.000.wav  ERROR: This video is unavailable.\n...
1164  YQb6N3HvbmgQ_580.000_590.000.wav  ERROR: This video is unavailable.\n...
1165   Y5iARe0XPQdg_95.000_105.000.wav  ERROR: This video is unavailable.\n...
1166    YmAg1_aL-fCY_30.000_40.000.wav  ERROR: This video is unavailable.\n...
1167  YxgQjEiwZsAk_146.000_156.000.wav  ERROR: This video is unavailable.\n...

How can I fix it?

**Comment by turpaultn** [comment]
Hi, 
These are normal. 
Sorry I forgot to took out last minute print (when I had some bugs).
You can now pull the changes (if you did run `pip install -e .` it should work without any added work).

Then, as stated in the [real folder](https://github.com/turpaultn/DESED/tree/master/real), you'll have to send me the missing_files at the end of the download by mail.

**Comment by turpaultn** [comment]
Sorry for closing the issue.
What I see from the errors however is that it seems no data has been downloaded at all from the validation set.
If that's the case (validation set is 1168 files (you should except less than 300 errors)) then do not hesitate to do this: 
(Taken from FAQ)

#### I have a problem downloading the recorded soundscapes. How do I do ? 
If you're in a country with youtube restrictions, you can try to use a VPN and the --proxy option from youtube-dl. You can also try to upgrade youtube-dl since it is regularly updated. Finally, if you succeeded to download most of the files, you can send the missing files as stated before in this page.

**Comment by turpaultn** [comment]
Excuse me, indeed it wasn't normal...
I had a mistake due to the 'Y' at the beginning of filenames (which is not present for the public eval set, but the download is not done with the script...)
I am fixing it in a pull request
